### ISSUE TITLE
 degree matrix?

### ISSUE THREAD

**Issue by yangjinray** [jx-zhong-for-academic-purpose/GCN-Anomaly-Detection#1]
Hi, in the paper, having the formula:

$$\widehat{\mathbf{A}}^{\mathbf{F}}=\widetilde{\mathbf{D}}^{\mathbf{F}-\frac{1}{2}} \widetilde{\mathbf{A}}^{\mathbf{F}} \widetilde{\mathbf{D}}^{\mathbf{F}-\frac{1}{2}}$$
 
but, the degree matrix D in which the entries outside the main diagonal are all zero, so if calculate
the formula: $\widetilde{\mathbf{D}}^{\mathbf{F}-\frac{1}{2}}$,  it will  be wrong.

can you explain it? thank you!

**Comment by jx-zhong-for-academic-purpose** [comment]
In practice, we follow the source codes of Kipf et al. (see the function **normalize_adj(adj)** at https://github.com/tkipf/gcn/blob/master/gcn/utils.py): set the "inf" elements as 0.
