### ISSUE TITLE
About reproduce the method

### ISSUE THREAD

**Issue by poweryin** [jx-zhong-for-academic-purpose/GCN-Anomaly-Detection#4]
Hi,Thanks for your great work.I want to reproduce this method.
looking forward to your source code.

**Comment by jx-zhong-for-academic-purpose** [comment]
We're still cleaning up the source codes, and the work should be finished before June 15th.

**Comment by poweryin** [comment]
Ok, Thanks for your work.
Best wishes

**Comment by jx-zhong-for-academic-purpose** [comment]
Our codes for feature extraction have been released! The training codes will be available as soon as possible.
