### ISSUE TITLE
About select high confidence snippets

### ISSUE THREAD

**Issue by poweryin** [jx-zhong-for-academic-purpose/GCN-Anomaly-Detection#6]
Hi,Thanks for your great work.I downloaded the extract feature code. I have some doubt. Firstly, the c3d_iter_1000.caffemodel file format you provided is a pcx image, not a binary file.
Secondly, in the cross-entropy error of direct supervision, In the paper ,H represents a set of high-confidence snippets. eg.C3D net ,So does the max value of |H| is the value 1600*60%？why does H plus absolute value mean ? I don't understand words in the paper"Due to the limited memory of GPUs,we at most sample 1600 high-confidence snippets with not more than 8 neighbors respectively in a video".Is an epoch selecting a 1600 high confidence snippets?what‘s the 8 neighbors mean？
Looking forward to your reply
Best wishes

**Comment by jx-zhong-for-academic-purpose** [comment]
1. c3d_iter_1000.caffemodel is a binary file, and it can be shown by Netron:
![image](https://user-images.githubusercontent.com/23209620/59970594-1e2a3f00-959d-11e9-9dc7-504f367232ba.png)
2. H plus absolute value means the cardinality of the set H.  For more details, you can visit https://en.wikipedia.org/wiki/Cardinality.
3. Your remaining problems will be addressed after our training codes is released.

**Comment by poweryin** [comment]
Thanks for your reply,I get it
