### ISSUE TITLE
about datasplit on shanghaitech dataset

### ISSUE THREAD

**Issue by wanboyang** [jx-zhong-for-academic-purpose/GCN-Anomaly-Detection#7]
Hi.   the appendix said that "The new data split is available at https://github.com/jx-zhong-foracademic-purpose/GCN-Anomaly-Detection." , but i didn't find the re-organized Shanghaitech dataset. May I have the new data split and its new indices? Thank you.

**Comment by jx-zhong-for-academic-purpose** [comment]
We add the new split at https://github.com/jx-zhong-for-academic-purpose/GCN-Anomaly-Detection/tree/master/ShanghaiTech_new_split
Thanks for attention

**Comment by wanboyang** [comment]
Thank you for your reply.
