### ISSUE TITLE
About the anomaly number

### ISSUE THREAD

**Issue by poweryin** [jx-zhong-for-academic-purpose/GCN-Anomaly-Detection#8]
Hi,Thanks for your great work.Since there is no test code, I can't see the result. So I have a question to verify my thoughts.I have a question.If there are two different types of anomaly events in a video, Can this model detect two different anomalies ?
Looking forward to your reply
Best Wishes
Thanks

**Comment by jx-zhong-for-academic-purpose** [comment]
Conceptually, it can. However, the standard task setting is a binary classification problem. In the experiment, we just comply with this setting.

**Comment by poweryin** [comment]
Ok, Thank you very much for your reply, I understand.
Best Wishes
